spring:
    datasource:
        url: jdbc:mysql://localhost/megasolution_db?serverTimezone=America/Argentina/Ushuaia
        username: admin
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
logging:
    level:
        org:
            hibernate:
                SQL: debug 

        #messages:
        #    encoding: UTF-8
        #    basename: data-jpa/src/main/resources/