spring:
    datasource:
        url: jdbc:mysql://localhost/megasolution_db?serverTimezone=America/Argentina/Ushuaia
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
    mvc:
        contentnegotiation:
            favor-parameter: true
            media-types.pdf: application/pdf
    mail:
        host: ${MAIL_HOST_MEGASOLUTION}
        port: 587
        username: ${MAIL_USERNAME_MEGASOLUTION}
        password: ${MAIL_PASSWORD_MEGASOLUTION}
        properties:
            mail:
                # debug: true
                encoding: UTF-8
                smtp:
                    auth: true
                    "[starttls.enable]": true #YAML_SHOULD_ESCAPE
                    "[starttls.required]": true
        
logging:
    pattern:
        console: -%clr(%d{HH:mm:ss.SSS dd-MM-yyyy}){blue} [%t] %clr(%-5level) %clr(%logger{36}){magenta} :%clr(%L){red} - %msg%n
    file:
        #path: ./logs // no se puede usar junto con flie.name, uno u otro
        name: ${HOME}/logs/app.log
    level:
        org:
            hibernate:
                # SQL: debug
